### ISSUE TITLE
 Reason: CORS preflight channel failed

### ISSUE THREAD

**Issue by Dhaval8087** [felixrieseberg/React-Dropzone-Component#66]
I have used Dropzone component in one of my component for upload the CSV.

as a postUrl I am passing my webservice url, domain is different 
I mean my site working on http://localhost:50130/Importcsv and I have given the URL http://localhost:8005//UploadFile

-I have checked with RestClient my Service is working fine but when I tried to give the same URL it gives me error 404(Not Foun) with following error in browser console 

**Cross- Origin application blocked : the Same Origin Policy is reading from the external source at http: // localhost: 8005 // Upload File TenantId = bc984c79 - d4f9-4dd6 - b8ad - f723aa2ba4af ​​& format = json not matter ? . ( Reason: CORS preflight channel failed ) .**

**Comment by felixrieseberg** [comment]
I assume that you need to work through CORS by adding a header to your service. Even if you're on the same domain, you're still hooking into a different port, meaning that cors would classify it as a different origin. 

In detail, your service needs the following: `"Access-Control-Allow-Origin": "*"`

(I'm closing this in the meantime, because we can't do anything here)
